#server:
#  port: ${SERVER_PORT}
#spring:
#  application:
#    name: storageservice
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    database: postgresql
#  datasource:
#    url: ${POSTGRES_URL}
#    username: ${POSTGRES_USERNAME}
#    password: ${POSTGRES_PASSWORD}
#    driver-class-name: org.postgresql.Driver
#  mail:
#    host: ${MAIL_HOST}
#    port: ${MAIL_PORT}
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#    debug: true
#
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#
#minio:
#  bucket: ${MINIO_BUCKET}
#  url: ${MINIO_URL}
#  accessKey: ${MINIO_ACCESS_KEY}
#  secretKey: ${MINIO_SECRET_KEY}
#
#jwt:
#  secretKey: ${JWT_SECRET_KEY}
#
#mail:
#  mailHost: ${MAIL_USERNAME}

server:
  port: 8081
spring:
  application:
    name: storageservice
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/storageservice
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  mail:
    host: smtp.mail.ru
    port: 587
    username: rentshopvehicle.webapplication@mail.ru
    password: jNwUztC2Kd2UC9QkDFC2
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    debug: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

minio:
  bucket: files
  url: http://localhost:9000
  accessKey: miniouser
  secretKey: miniosecret

jwt:
  secretKey: 5a2a9a5ddd3770c952bb801ec55a942e056e7810b4e2dad37be21e8d99ca8bd6

mail:
  mailHost: rentshopvehicle.webapplication@mail.ru
