version: "3.9"

#services:
#  app:
#    build:
#      context: .
#    env_file:
#      - .env
#  postgres:
#    container_name: postgres-db
#    image: postgres:latest
#    restart: unless-stopped
#    environment:
#      POSTGRES_DB: ${POSTGRES_DATABASE}
#      POSTGRES_USER: ${POSTGRES_USERNAME}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#    ports:
#      - "5432:5432"
#  minio:
#    image: minio/minio:latest
#    container_name: minio
#    environment:
#      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
#      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
#    command: server /minio --console-address :9090
#    ports:
#      - "9090:9090"
#      - "9000:9000"

services:

  postgres:
    container_name: postgres-db
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: storageservice
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: miniouser
      MINIO_ROOT_PASSWORD: miniosecret
    command: server /minio --console-address :9090
    ports:
      - "9090:9090"
      - "9000:9000"